algos:

#  BTC-XAU-EU50-JPY_1H:
#    script_path: "CEHourly_BTC+XAU+EU50+UJ.py"

  CE_XAU_5M:
    script_path: "CEStrategy_XAU_5M.py"

  CE_Reverse_XAU_5M:
    script_path: "CEStrategyReverse_XAU_5M.py"

  EMA_VWAP_Scalp:
    script_path: "EMA-VWAP_Scalp.py"

  CE-1H-15M_MultiAssets:
    script_path: "CE-1H-15M_MultiAssets.py"